name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  netlify:
    uses: yoriiis/actions/.github/workflows/netlify-deploy.yml@main
    with:
      node-version: 12.14
      build-dir: netlify
      command-build: |
        npm run build
        npm run build:netlify
        cp -r dist/ netlify/assets/
    secrets:
      NETLIFY_APP_ID: ${{ secrets.NETLIFY_APP_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
